import { describe, expect, it } from 'vitest';
import {
  compactBehaviorTree,
  compactBlueprint,
  compactGenericExtraction,
  compactMaterial,
  compactStateTree,
  compactWidgetBlueprint,
} from '../src/compactor.js';

describe('compactor helpers', () => {
  it('strips guid and position fields recursively from generic extraction payloads', () => {
    const payload = {
      success: true,
      dataAsset: {
        itemGuid: 'item-guid-1',
        editorData: {
          posX: 10,
          posY: 20,
        },
        entries: [
          {
            valueGuid: 'value-guid-1',
            metadata: {},
            children: [],
          },
        ],
        emptyObject: {},
        emptyArray: [],
      },
    };

    const compacted = compactGenericExtraction(payload) as typeof payload;

    expect(compacted.dataAsset.itemGuid).toBeUndefined();
    expect(compacted.dataAsset.editorData).toBeUndefined();
    expect(compacted.dataAsset.entries[0]?.valueGuid).toBeUndefined();
    expect(compacted.dataAsset.entries[0]?.metadata).toBeUndefined();
    expect(compacted.dataAsset.entries[0]?.children).toBeUndefined();
    expect(compacted.dataAsset.emptyObject).toBeUndefined();
    expect(compacted.dataAsset.emptyArray).toBeUndefined();
  });

  it('compacts material graphs by shortening expression references and stripping layout noise', () => {
    const payload = {
      success: true,
      material: {
        assetPath: '/Game/Materials/M_Test',
        parameterGuid: 'param-guid-1',
        expressions: [
          {
            expressionGuid: 'expr-guid-1',
            posX: 16,
            posY: 24,
            class: '/Script/Engine.MaterialExpressionScalarParameter',
          },
          {
            expressionGuid: 'expr-guid-2',
            materialExpressionGuid: 'expr-guid-2',
            inputs: [
              {
                expressionGuid: 'expr-guid-1',
                outputIndex: 0,
              },
            ],
          },
        ],
        propertyConnections: [
          {
            expressionGuid: 'expr-guid-2',
            outputIndex: 1,
          },
        ],
        comments: [],
      },
    };

    const compacted = compactMaterial(payload) as typeof payload & {
      material: {
        expressions: Array<Record<string, unknown>>;
        propertyConnections: Array<Record<string, unknown>>;
      };
    };

    expect(compacted.material.parameterGuid).toBeUndefined();
    expect(compacted.material.comments).toBeUndefined();
    expect(compacted.material.expressions[0]?.id).toBe('e0');
    expect(compacted.material.expressions[0]?.expressionGuid).toBeUndefined();
    expect(compacted.material.expressions[0]?.posX).toBeUndefined();
    expect(compacted.material.expressions[1]?.id).toBe('e1');
    expect(compacted.material.expressions[1]?.materialExpressionGuid).toBeUndefined();
    expect(compacted.material.expressions[1]?.inputs).toEqual([
      {
        expressionId: 'e0',
        outputIndex: 0,
      },
    ]);
    expect(compacted.material.propertyConnections).toEqual([
      {
        expressionId: 'e1',
        outputIndex: 1,
      },
    ]);
  });

  // --- C5: Additional compactor edge case tests ---

  it('compactBlueprint replaces nodeGuids with short IDs and strips positional data', () => {
    const data = {
      blueprint: {
        functions: [{
          graphGuid: 'graph-001',
          nodes: [
            {
              nodeGuid: 'node-aaa',
              posX: 100,
              posY: 200,
              nodeComment: '',
              pins: [{
                pinId: 'pin-001',
                autogeneratedDefaultValue: 'auto',
                defaultValue: '',
                type: { category: 'exec', sub_category: '' },
                connections: [],
              }],
            },
            {
              nodeGuid: 'node-bbb',
              posX: 300,
              posY: 400,
              nodeComment: 'Keep this comment',
              pins: [{
                pinId: 'pin-002',
                defaultValue: '42',
                type: { category: 'int', sub_category: 'mine' },
                connections: [{
                  nodeGuid: 'node-aaa',
                  pinId: 'pin-001',
                }],
              }],
            },
          ],
        }],
      },
    };

    const compacted = compactBlueprint(data) as any;
    const graph = compacted.blueprint.functions[0];

    expect(graph.graphGuid).toBeUndefined();
    expect(graph.nodes[0].id).toBe('n0');
    expect(graph.nodes[0].nodeGuid).toBeUndefined();
    expect(graph.nodes[0].posX).toBeUndefined();
    expect(graph.nodes[0].posY).toBeUndefined();
    expect(graph.nodes[0].nodeComment).toBeUndefined();
    expect(graph.nodes[0].pins[0].pinId).toBeUndefined();
    expect(graph.nodes[0].pins[0].autogeneratedDefaultValue).toBeUndefined();
    expect(graph.nodes[0].pins[0].defaultValue).toBeUndefined();
    expect(graph.nodes[0].pins[0].type).toBe('exec');
    expect(graph.nodes[0].pins[0].connections).toBeUndefined();
    expect(graph.nodes[1].id).toBe('n1');
    expect(graph.nodes[1].nodeComment).toBe('Keep this comment');
    expect(graph.nodes[1].pins[0].defaultValue).toBe('42');
    expect(graph.nodes[1].pins[0].type).toEqual({ category: 'int', sub_category: 'mine' });
    expect(graph.nodes[1].pins[0].connections[0].nodeGuid).toBe('n0');
  });

  it('compactBlueprint returns non-object data unchanged', () => {
    expect(compactBlueprint(null)).toBeNull();
    expect(compactBlueprint('string')).toBe('string');
    expect(compactBlueprint(42)).toBe(42);
  });

  it('compactBlueprint handles object with no blueprint key', () => {
    const data = { other: 'data' };
    expect(compactBlueprint(data)).toEqual({ other: 'data' });
  });

  it('compactWidgetBlueprint compacts the widget tree and functions', () => {
    const data = {
      rootWidget: {
        name: 'Root',
        displayLabel: 'Root',
        visibility: 'Visible',
        properties: {},
        children: [{
          name: 'Child',
          displayLabel: '',
          visibility: 'Hidden',
          properties: { text: 'Hello' },
          children: [],
        }],
      },
      functions: [{
        graphGuid: 'g1',
        nodes: [{
          nodeGuid: 'n1',
          posX: 10,
          posY: 20,
          nodeComment: '',
          pins: [],
        }],
      }],
      bindings: {},
      animations: [],
      compile: {
        errors: [],
        warnings: [],
        messages: [],
      },
    };

    const compacted = compactWidgetBlueprint(data) as any;

    expect(compacted.rootWidget.displayLabel).toBeUndefined();
    expect(compacted.rootWidget.visibility).toBeUndefined();
    expect(compacted.rootWidget.properties).toBeUndefined();
    expect(compacted.rootWidget.children[0].displayLabel).toBeUndefined();
    expect(compacted.rootWidget.children[0].visibility).toBe('Hidden');
    expect(compacted.rootWidget.children[0].properties).toEqual({ text: 'Hello' });
    expect(compacted.functions[0].graphGuid).toBeUndefined();
    expect(compacted.functions[0].nodes[0].id).toBe('n0');
    expect(compacted.bindings).toBeUndefined();
    expect(compacted.animations).toBeUndefined();
    expect(compacted.compile.errors).toBeUndefined();
  });

  it('compactWidgetBlueprint returns non-object data unchanged', () => {
    expect(compactWidgetBlueprint(null)).toBeNull();
    expect(compactWidgetBlueprint(42)).toBe(42);
  });

  it('compactBehaviorTree strips nodeIndex, executionIndex, and empty collections', () => {
    const data = {
      schemaVersion: '1.0',
      behaviorTree: {
        rootNode: {
          nodeClass: 'Selector',
          nodeIndex: 0,
          executionIndex: 0,
          properties: {},
          services: [],
          decorators: [],
          children: [{
            nodeClass: 'Task',
            nodeIndex: 1,
            executionIndex: 1,
            properties: { key: 'value' },
            decoratorLogic: [],
            services: [],
            decorators: [],
            children: [],
          }],
        },
      },
    };

    const compacted = compactBehaviorTree(data) as any;

    expect(compacted.schemaVersion).toBeUndefined();
    const root = compacted.behaviorTree.rootNode;
    expect(root.nodeIndex).toBeUndefined();
    expect(root.executionIndex).toBeUndefined();
    expect(root.properties).toBeUndefined();
    expect(root.services).toBeUndefined();
    expect(root.decorators).toBeUndefined();
    expect(root.children[0].nodeIndex).toBeUndefined();
    expect(root.children[0].executionIndex).toBeUndefined();
    expect(root.children[0].properties).toEqual({ key: 'value' });
    expect(root.children[0].decoratorLogic).toBeUndefined();
    expect(root.children[0].services).toBeUndefined();
    expect(root.children[0].decorators).toBeUndefined();
    expect(root.children[0].children).toBeUndefined();
  });

  it('compactBehaviorTree returns non-object data unchanged', () => {
    expect(compactBehaviorTree(null)).toBeNull();
    expect(compactBehaviorTree('hello')).toBe('hello');
  });

  it('compactBehaviorTree handles missing behaviorTree key gracefully', () => {
    const data = { other: 'data' };
    expect(compactBehaviorTree(data)).toEqual({ other: 'data' });
  });

  it('compactStateTree strips schemaVersion and compacts state tree nodes', () => {
    const data = {
      schemaVersion: '2.0',
      stateTree: {
        evaluators: [{
          expressionIndent: 0,
          nodeProperties: {},
          instanceProperties: {},
        }],
        globalTasks: [{
          expressionIndent: 1,
          nodeProperties: { key: 'val' },
          instanceProperties: {},
        }],
        states: [{
          name: 'Idle',
          tasks: [{
            expressionIndent: 0,
            nodeProperties: {},
            instanceProperties: {},
          }],
          enterConditions: [],
          considerations: [],
          transitions: [{
            conditions: [{
              expressionIndent: 0,
              nodeProperties: {},
              instanceProperties: {},
            }],
          }],
          children: [],
        }],
      },
    };

    const compacted = compactStateTree(data) as any;

    expect(compacted.schemaVersion).toBeUndefined();
    const st = compacted.stateTree;
    expect(st.evaluators[0].expressionIndent).toBeUndefined();
    expect(st.evaluators[0].nodeProperties).toBeUndefined();
    expect(st.evaluators[0].instanceProperties).toBeUndefined();
    expect(st.globalTasks[0].expressionIndent).toBe(1);
    expect(st.globalTasks[0].nodeProperties).toEqual({ key: 'val' });
    expect(st.globalTasks[0].instanceProperties).toBeUndefined();
    const state = st.states[0];
    // tasks has one entry whose properties were stripped to {} — the array is [{}], not empty
    expect(state.tasks).toEqual([{}]);
    expect(state.enterConditions).toBeUndefined();
    expect(state.considerations).toBeUndefined();
    // transitions has one entry whose conditions were compacted to [{}] (not empty)
    expect(state.transitions).toEqual([{ conditions: [{}] }]);
    expect(state.children).toBeUndefined();
  });

  it('compactStateTree returns non-object data unchanged', () => {
    expect(compactStateTree(null)).toBeNull();
    expect(compactStateTree(123)).toBe(123);
  });

  it('compactStateTree handles missing stateTree key gracefully', () => {
    const data = { other: 'data' };
    expect(compactStateTree(data)).toEqual({ other: 'data' });
  });

  it('compactGenericExtraction handles empty input object', () => {
    const result = compactGenericExtraction({});
    expect(result).toEqual({});
  });

  it('compactGenericExtraction strips nested guids and positions from deep structures', () => {
    const data = {
      level1: {
        itemGuid: 'guid1',
        posX: 5,
        value: 42,
        level2: {
          entryGuid: 'guid2',
          posY: 10,
          name: 'test',
        },
      },
    };

    const compacted = compactGenericExtraction(data) as any;
    expect(compacted.level1.itemGuid).toBeUndefined();
    expect(compacted.level1.posX).toBeUndefined();
    expect(compacted.level1.value).toBe(42);
    expect(compacted.level1.level2.entryGuid).toBeUndefined();
    expect(compacted.level1.level2.posY).toBeUndefined();
    expect(compacted.level1.level2.name).toBe('test');
  });

  it('compactMaterial falls back to generic extraction when no material graph root is found', () => {
    const data = {
      success: true,
      unknown: {
        itemGuid: 'guid1',
        posX: 10,
        name: 'test',
      },
    };

    const compacted = compactMaterial(data) as any;
    expect(compacted.unknown.itemGuid).toBeUndefined();
    expect(compacted.unknown.posX).toBeUndefined();
    expect(compacted.unknown.name).toBe('test');
  });

  it('compactMaterial returns non-object data unchanged', () => {
    expect(compactMaterial(null)).toBeNull();
    expect(compactMaterial('text')).toBe('text');
  });

  it('compactBlueprint does not strip object-typed propertyOverrides from components', () => {
    const payload = {
      blueprint: {
        components: [{
          componentName: 'StateTree',
          componentClass: '/Script/GameplayStateTreeModule.StateTreeComponent',
          propertyOverrides: {
            bStartLogicAutomatically: false,
            'StateTreeRef.StateTree': '/Game/AI/ST_Referee.ST_Referee',
          },
        }],
        functions: [],
      },
    };

    const compacted = compactBlueprint(payload) as typeof payload;

    const stComp = compacted.blueprint.components.find((c) => c.componentName === 'StateTree');
    expect(stComp).toBeDefined();
    expect(stComp!.propertyOverrides).toBeDefined();
    expect(stComp!.propertyOverrides['StateTreeRef.StateTree']).toBe('/Game/AI/ST_Referee.ST_Referee');
    expect(stComp!.propertyOverrides.bStartLogicAutomatically).toBe(false);
  });
});
