import { describe, expect, it, vi } from 'vitest';
import { z } from 'zod';
import { registerExtractionTools } from '../src/tools/extraction.js';
import { createToolRegistry, parseDirectToolResult } from './tool-module-test-helpers.js';
import { getTextContent } from './test-helpers.js';

const scopeEnum = z.enum(['ClassLevel', 'Variables', 'Full']);
const extractAssetTypeSchema = z.enum([
  'statetree',
  'data_asset',
  'data_table',
  'behavior_tree',
  'blackboard',
  'user_defined_struct',
  'user_defined_enum',
  'curve',
  'curve_table',
  'material_instance',
  'anim_sequence',
  'anim_montage',
  'blend_space',
]);
const cascadeResultSchema = z.object({}).passthrough();

describe('registerExtractionTools', () => {
  it('forwards extract_blueprint arguments and compacts graph output', async () => {
    const registry = createToolRegistry();
    const callSubsystemJson = vi.fn(async () => ({
      blueprint: {
        functions: [{
          graphGuid: 'graph-guid',
          nodes: [{
            nodeGuid: 'node-guid',
            posX: 10,
            posY: 20,
            nodeComment: '',
            pins: [{
              pinId: 'pin-guid',
              autogeneratedDefaultValue: '',
              defaultValue: '',
              type: { category: 'exec', sub_category: '' },
              connections: [],
            }],
          }],
        }],
      },
    }));

    registerExtractionTools({
      server: registry.server,
      callSubsystemJson,
      scopeEnum,
      extractAssetTypeSchema,
      cascadeResultSchema,
    });

    const result = await registry.getTool('extract_blueprint').handler({
      asset_path: '/Game/Test/BP_Test',
      scope: 'Full',
      graph_filter: ['EventGraph'],
      compact: true,
      include_class_defaults: true,
    });

    expect(callSubsystemJson).toHaveBeenCalledWith('ExtractBlueprint', {
      AssetPath: '/Game/Test/BP_Test',
      Scope: 'Full',
      GraphFilter: 'EventGraph',
      bIncludeClassDefaults: true,
    });
    expect(parseDirectToolResult(result)).toMatchObject({
      blueprint: {
        functions: [{
          nodes: [{
            id: 'n0',
            pins: [{ type: 'exec' }],
          }],
        }],
      },
    });
  });

  it('compacts routed extract_asset payloads with the generic stripper', async () => {
    const registry = createToolRegistry();
    const callSubsystemJson = vi.fn(async () => ({
      dataAsset: {
        entryGuid: 'entry-guid',
        editorData: {
          posX: 12,
          posY: 24,
        },
        emptyObject: {},
      },
    }));

    registerExtractionTools({
      server: registry.server,
      callSubsystemJson,
      scopeEnum,
      extractAssetTypeSchema,
      cascadeResultSchema,
    });

    const result = await registry.getTool('extract_asset').handler({
      asset_type: 'data_asset',
      asset_path: '/Game/Data/DA_Test',
      compact: true,
    });

    expect(callSubsystemJson).toHaveBeenCalledWith('ExtractDataAsset', {
      AssetPath: '/Game/Data/DA_Test',
    });
    expect(parseDirectToolResult(result)).toEqual({});
  });

  it('truncates oversized data table responses', async () => {
    const registry = createToolRegistry();
    const callSubsystemJson = vi.fn(async () => ({
      rows: [{
        summary: 'x'.repeat(220_000),
      }],
    }));

    registerExtractionTools({
      server: registry.server,
      callSubsystemJson,
      scopeEnum,
      extractAssetTypeSchema,
      cascadeResultSchema,
    });

    const result = await registry.getTool('extract_asset').handler({
      asset_type: 'data_table',
      asset_path: '/Game/Data/DT_Large',
      compact: false,
    });

    expect(getTextContent(result as { content?: Array<{ text?: string; type: string }> })).toContain('[TRUNCATED]');
  });

  it('surfaces subsystem failures through jsonToolError', async () => {
    const registry = createToolRegistry();
    const callSubsystemJson = vi.fn(async () => {
      throw new Error('search failed');
    });

    registerExtractionTools({
      server: registry.server,
      callSubsystemJson,
      scopeEnum,
      extractAssetTypeSchema,
      cascadeResultSchema,
    });

    const result = await registry.getTool('search_assets').handler({
      query: 'Player',
      class_filter: 'Blueprint',
      max_results: 5,
    });

    expect((result as { isError?: boolean }).isError).toBe(true);
    expect(getTextContent(result as { content?: Array<{ text?: string; type: string }> })).toContain('search failed');
  });
});
