import { describe, expect, it, vi } from 'vitest';
import { z } from 'zod';
import { registerExtractionTools } from '../src/tools/extraction.js';
import { createToolRegistry, parseDirectToolResult } from './tool-module-test-helpers.js';
import { getTextContent } from './test-helpers.js';

const scopeEnum = z.enum(['ClassLevel', 'Variables', 'Full']);
const extractAssetTypeSchema = z.enum([
  'statetree',
  'data_asset',
  'data_table',
  'behavior_tree',
  'blackboard',
  'user_defined_struct',
  'user_defined_enum',
  'curve',
  'curve_table',
  'material_instance',
  'anim_sequence',
  'anim_montage',
  'blend_space',
]);
const cascadeResultSchema = z.object({}).passthrough();

describe('registerExtractionTools', () => {
  it('forwards extract_blueprint arguments and compacts graph output', async () => {
    const registry = createToolRegistry();
    const callSubsystemJson = vi.fn(async () => ({
      blueprint: {
        functions: [{
          graphGuid: 'graph-guid',
          nodes: [{
            nodeGuid: 'node-guid',
            posX: 10,
            posY: 20,
            nodeComment: '',
            pins: [{
              pinId: 'pin-guid',
              autogeneratedDefaultValue: '',
              defaultValue: '',
              type: { category: 'exec', sub_category: '' },
              connections: [],
            }],
          }],
        }],
      },
    }));

    registerExtractionTools({
      server: registry.server,
      callSubsystemJson,
      scopeEnum,
      extractAssetTypeSchema,
      cascadeResultSchema,
      toolHelpRegistry: registry.toolHelpRegistry,
    });

    const result = await registry.getTool('extract_blueprint').handler({
      asset_path: '/Game/Test/BP_Test',
      scope: 'Full',
      graph_filter: ['EventGraph'],
      compact: true,
      include_class_defaults: true,
    });

    expect(callSubsystemJson).toHaveBeenCalledWith('ExtractBlueprint', {
      AssetPath: '/Game/Test/BP_Test',
      Scope: 'Full',
      GraphFilter: 'EventGraph',
      bIncludeClassDefaults: true,
    });
    expect(parseDirectToolResult(result)).toMatchObject({
      blueprint: {
        functions: [{
          nodes: [{
            id: 'n0',
            pins: [{ type: 'exec' }],
          }],
        }],
      },
    });
  });

  it('declares compact default as true on extract_blueprint', () => {
    const registry = createToolRegistry();
    registerExtractionTools({
      server: registry.server,
      callSubsystemJson: vi.fn(),
      scopeEnum,
      extractAssetTypeSchema,
      cascadeResultSchema,
      toolHelpRegistry: registry.toolHelpRegistry,
    });
    const schema = registry.getTool('extract_blueprint').config.inputSchema as Record<string, z.ZodTypeAny>;
    expect(schema.compact._def.defaultValue()).toBe(true);
  });

  it('returns raw blueprint output when compact is false', async () => {
    const registry = createToolRegistry();
    const callSubsystemJson = vi.fn(async () => ({
      blueprint: {
        functions: [{
          graphGuid: 'graph-guid',
          nodes: [{
            nodeGuid: 'node-guid',
            posX: 10,
            posY: 20,
            pins: [],
          }],
        }],
      },
    }));

    registerExtractionTools({
      server: registry.server,
      callSubsystemJson,
      scopeEnum,
      extractAssetTypeSchema,
      cascadeResultSchema,
      toolHelpRegistry: registry.toolHelpRegistry,
    });

    const result = await registry.getTool('extract_blueprint').handler({
      asset_path: '/Game/Test/BP_Test',
      scope: 'Full',
      compact: false,
    });

    const parsed = parseDirectToolResult(result);
    expect(parsed).toMatchObject({
      blueprint: {
        functions: [{
          graphGuid: 'graph-guid',
          nodes: [{ nodeGuid: 'node-guid', posX: 10, posY: 20 }],
        }],
      },
    });
  });

  it('compacts routed extract_asset payloads with the generic stripper', async () => {
    const registry = createToolRegistry();
    const callSubsystemJson = vi.fn(async () => ({
      dataAsset: {
        entryGuid: 'entry-guid',
        editorData: {
          posX: 12,
          posY: 24,
        },
        emptyObject: {},
      },
    }));

    registerExtractionTools({
      server: registry.server,
      callSubsystemJson,
      scopeEnum,
      extractAssetTypeSchema,
      cascadeResultSchema,
      toolHelpRegistry: registry.toolHelpRegistry,
    });

    const result = await registry.getTool('extract_asset').handler({
      asset_type: 'data_asset',
      asset_path: '/Game/Data/DA_Test',
      compact: true,
    });

    expect(callSubsystemJson).toHaveBeenCalledWith('ExtractDataAsset', {
      AssetPath: '/Game/Data/DA_Test',
    });
    expect(parseDirectToolResult(result)).toEqual({});
  });

  it('declares compact default as true on extract_asset', () => {
    const registry = createToolRegistry();
    registerExtractionTools({
      server: registry.server,
      callSubsystemJson: vi.fn(),
      scopeEnum,
      extractAssetTypeSchema,
      cascadeResultSchema,
      toolHelpRegistry: registry.toolHelpRegistry,
    });
    const schema = registry.getTool('extract_asset').config.inputSchema as Record<string, z.ZodTypeAny>;
    expect(schema.compact._def.defaultValue()).toBe(true);
  });

  it('returns raw extract_asset output when compact is false', async () => {
    const registry = createToolRegistry();
    const callSubsystemJson = vi.fn(async () => ({
      dataAsset: {
        entryGuid: 'entry-guid',
        editorData: {
          posX: 12,
          posY: 24,
        },
      },
    }));

    registerExtractionTools({
      server: registry.server,
      callSubsystemJson,
      scopeEnum,
      extractAssetTypeSchema,
      cascadeResultSchema,
      toolHelpRegistry: registry.toolHelpRegistry,
    });

    const result = await registry.getTool('extract_asset').handler({
      asset_type: 'data_asset',
      asset_path: '/Game/Data/DA_Test',
      compact: false,
    });

    expect(parseDirectToolResult(result)).toMatchObject({
      dataAsset: {
        entryGuid: 'entry-guid',
        editorData: { posX: 12, posY: 24 },
      },
    });
  });

  it('truncates oversized data table responses', async () => {
    const registry = createToolRegistry();
    const callSubsystemJson = vi.fn(async () => ({
      rows: [{
        summary: 'x'.repeat(220_000),
      }],
    }));

    registerExtractionTools({
      server: registry.server,
      callSubsystemJson,
      scopeEnum,
      extractAssetTypeSchema,
      cascadeResultSchema,
      toolHelpRegistry: registry.toolHelpRegistry,
    });

    const result = await registry.getTool('extract_asset').handler({
      asset_type: 'data_table',
      asset_path: '/Game/Data/DT_Large',
      compact: false,
    });

    expect(getTextContent(result as { content?: Array<{ text?: string; type: string }> })).toContain('Warning');
  });

  it('large extract_blueprint preserves structuredContent with truncation warning', async () => {
    const registry = createToolRegistry();
    const largeBlueprint = { functions: Array(500).fill({ name: 'fn', graph: 'x'.repeat(1000) }) };
    const callSubsystemJson = vi.fn(async () => largeBlueprint);

    registerExtractionTools({
      server: registry.server,
      callSubsystemJson,
      scopeEnum,
      extractAssetTypeSchema,
      cascadeResultSchema,
      toolHelpRegistry: registry.toolHelpRegistry,
    });

    const result = await registry.getTool('extract_blueprint').handler({
      asset_path: '/Game/Test/BP_Large',
      scope: 'Full',
      compact: false,
    });

    const r = result as { structuredContent?: unknown; content?: Array<{ text?: string; type: string }> };
    expect(r.structuredContent).toBeDefined();
    const text = getTextContent(r);
    expect(text).toContain('Warning');
    expect(text).toMatch(/narrower scope/i);
  });

  it('large extract_asset data_table preserves structuredContent with truncation warning', async () => {
    const registry = createToolRegistry();
    const callSubsystemJson = vi.fn(async () => ({
      rows: [{ summary: 'x'.repeat(220_000) }],
    }));

    registerExtractionTools({
      server: registry.server,
      callSubsystemJson,
      scopeEnum,
      extractAssetTypeSchema,
      cascadeResultSchema,
      toolHelpRegistry: registry.toolHelpRegistry,
    });

    const result = await registry.getTool('extract_asset').handler({
      asset_type: 'data_table',
      asset_path: '/Game/Data/DT_Large',
      compact: false,
    });

    const r = result as { structuredContent?: unknown; content?: Array<{ text?: string; type: string }> };
    expect(r.structuredContent).toBeDefined();
    const text = getTextContent(r);
    expect(text).toContain('Warning');
  });

  it('surfaces subsystem failures through jsonToolError', async () => {
    const registry = createToolRegistry();
    const callSubsystemJson = vi.fn(async () => {
      throw new Error('search failed');
    });

    registerExtractionTools({
      server: registry.server,
      callSubsystemJson,
      scopeEnum,
      extractAssetTypeSchema,
      cascadeResultSchema,
      toolHelpRegistry: registry.toolHelpRegistry,
    });

    const result = await registry.getTool('search_assets').handler({
      query: 'Player',
      class_filter: 'Blueprint',
      max_results: 5,
    });

    expect((result as { isError?: boolean }).isError).toBe(true);
    expect(getTextContent(result as { content?: Array<{ text?: string; type: string }> })).toContain('search failed');
  });

  it('forwards extract_material arguments with verbose and compact flags', async () => {
    const registry = createToolRegistry();
    const callSubsystemJson = vi.fn(async () => ({
      materialName: 'M_Base',
      expressions: [{ guid: 'expr-guid', posX: 10, posY: 20 }],
    }));

    registerExtractionTools({
      server: registry.server,
      callSubsystemJson,
      scopeEnum,
      extractAssetTypeSchema,
      cascadeResultSchema,
      toolHelpRegistry: registry.toolHelpRegistry,
    });

    const result = await registry.getTool('extract_material').handler({
      asset_path: '/Game/Materials/M_Base',
      verbose: true,
      compact: false,
    });

    expect(callSubsystemJson).toHaveBeenCalledWith('ExtractMaterial', {
      AssetPath: '/Game/Materials/M_Base',
      bVerbose: true,
    });
    expect(parseDirectToolResult(result)).toMatchObject({
      materialName: 'M_Base',
    });
  });

  it('returns an error when extract_material fails', async () => {
    const registry = createToolRegistry();
    const callSubsystemJson = vi.fn(async () => {
      throw new Error('material not found');
    });

    registerExtractionTools({
      server: registry.server,
      callSubsystemJson,
      scopeEnum,
      extractAssetTypeSchema,
      cascadeResultSchema,
      toolHelpRegistry: registry.toolHelpRegistry,
    });

    const result = await registry.getTool('extract_material').handler({
      asset_path: '/Game/Materials/M_Missing',
      verbose: false,
      compact: false,
    });

    expect((result as { isError?: boolean }).isError).toBe(true);
    expect(getTextContent(result as { content?: Array<{ text?: string; type: string }> })).toContain('material not found');
  });

  it('routes extract_material with asset_kind function to ExtractMaterialFunction', async () => {
    const registry = createToolRegistry();
    const callSubsystemJson = vi.fn(async () => ({
      functionName: 'MF_Test',
      expressions: [],
    }));

    registerExtractionTools({
      server: registry.server,
      callSubsystemJson,
      scopeEnum,
      extractAssetTypeSchema,
      cascadeResultSchema,
      toolHelpRegistry: registry.toolHelpRegistry,
    });

    await registry.getTool('extract_material').handler({
      asset_path: '/Game/Materials/MF_Test',
      asset_kind: 'function',
      verbose: true,
      compact: false,
    });

    expect(callSubsystemJson).toHaveBeenCalledWith('ExtractMaterialFunction', {
      AssetPath: '/Game/Materials/MF_Test',
      bVerbose: true,
    });
  });

  it('routes extract_material with asset_kind layer to ExtractMaterialFunction', async () => {
    const registry = createToolRegistry();
    const callSubsystemJson = vi.fn(async () => ({
      layerName: 'ML_Test',
    }));

    registerExtractionTools({
      server: registry.server,
      callSubsystemJson,
      scopeEnum,
      extractAssetTypeSchema,
      cascadeResultSchema,
      toolHelpRegistry: registry.toolHelpRegistry,
    });

    await registry.getTool('extract_material').handler({
      asset_path: '/Game/Materials/ML_Test',
      asset_kind: 'layer',
      verbose: false,
      compact: false,
    });

    expect(callSubsystemJson).toHaveBeenCalledWith('ExtractMaterialFunction', {
      AssetPath: '/Game/Materials/ML_Test',
      bVerbose: false,
    });
  });

  it('routes extract_material with asset_kind layer_blend to ExtractMaterialFunction', async () => {
    const registry = createToolRegistry();
    const callSubsystemJson = vi.fn(async () => ({
      blendName: 'MLB_Test',
    }));

    registerExtractionTools({
      server: registry.server,
      callSubsystemJson,
      scopeEnum,
      extractAssetTypeSchema,
      cascadeResultSchema,
      toolHelpRegistry: registry.toolHelpRegistry,
    });

    await registry.getTool('extract_material').handler({
      asset_path: '/Game/Materials/MLB_Test',
      asset_kind: 'layer_blend',
      verbose: false,
      compact: false,
    });

    expect(callSubsystemJson).toHaveBeenCalledWith('ExtractMaterialFunction', {
      AssetPath: '/Game/Materials/MLB_Test',
      bVerbose: false,
    });
  });

  it('forwards extract_cascade with asset_paths and returns a structured manifest', async () => {
    const registry = createToolRegistry();
    const callSubsystemJson = vi.fn(async () => ({
      manifest: [
        { assetPath: '/Game/BP_A', status: 'extracted' },
        { assetPath: '/Game/BP_B', status: 'skipped' },
      ],
      total_count: 2,
      extracted_count: 1,
      skipped_count: 1,
      output_directory: '/tmp/cascade',
    }));

    registerExtractionTools({
      server: registry.server,
      callSubsystemJson,
      scopeEnum,
      extractAssetTypeSchema,
      cascadeResultSchema,
      toolHelpRegistry: registry.toolHelpRegistry,
    });

    const result = await registry.getTool('extract_cascade').handler({
      asset_paths: ['/Game/BP_A', '/Game/BP_B'],
      scope: 'Full',
      max_depth: 2,
      compact: false,
    });

    expect(callSubsystemJson).toHaveBeenCalledWith('ExtractCascade', {
      AssetPathsJson: JSON.stringify(['/Game/BP_A', '/Game/BP_B']),
      Scope: 'Full',
      MaxDepth: 2,
      GraphFilter: '',
    });
    expect(parseDirectToolResult(result)).toMatchObject({
      extracted_count: 1,
      skipped_count: 1,
      total_count: 2,
      output_directory: '/tmp/cascade',
    });
  });

  it('declares compact default as true on extract_cascade', () => {
    const registry = createToolRegistry();
    registerExtractionTools({
      server: registry.server,
      callSubsystemJson: vi.fn(),
      scopeEnum,
      extractAssetTypeSchema,
      cascadeResultSchema,
      toolHelpRegistry: registry.toolHelpRegistry,
    });
    const schema = registry.getTool('extract_cascade').config.inputSchema as Record<string, z.ZodTypeAny>;
    expect(schema.compact._def.defaultValue()).toBe(true);
  });

  it('returns an error when extract_cascade fails', async () => {
    const registry = createToolRegistry();
    const callSubsystemJson = vi.fn(async () => {
      throw new Error('cascade extraction failed');
    });

    registerExtractionTools({
      server: registry.server,
      callSubsystemJson,
      scopeEnum,
      extractAssetTypeSchema,
      cascadeResultSchema,
      toolHelpRegistry: registry.toolHelpRegistry,
    });

    const result = await registry.getTool('extract_cascade').handler({
      asset_paths: ['/Game/BP_Missing'],
      scope: 'Full',
      max_depth: 1,
      compact: false,
    });

    expect((result as { isError?: boolean }).isError).toBe(true);
    expect(getTextContent(result as { content?: Array<{ text?: string; type: string }> })).toContain('cascade extraction failed');
  });

  it('forwards list_assets arguments to the subsystem', async () => {
    const registry = createToolRegistry();
    const callSubsystemJson = vi.fn(async () => ({
      assets: [
        { assetPath: '/Game/Blueprints/BP_Player', className: 'Blueprint' },
      ],
    }));

    registerExtractionTools({
      server: registry.server,
      callSubsystemJson,
      scopeEnum,
      extractAssetTypeSchema,
      cascadeResultSchema,
      toolHelpRegistry: registry.toolHelpRegistry,
    });

    const result = await registry.getTool('list_assets').handler({
      package_path: '/Game/Blueprints',
      recursive: true,
      class_filter: 'Blueprint',
    });

    expect(callSubsystemJson).toHaveBeenCalledWith('ListAssets', {
      PackagePath: '/Game/Blueprints',
      bRecursive: true,
      ClassFilter: 'Blueprint',
    });
    expect(parseDirectToolResult(result)).toMatchObject({
      assets: [{ assetPath: '/Game/Blueprints/BP_Player' }],
    });
  });

  it('returns an error when list_assets fails', async () => {
    const registry = createToolRegistry();
    const callSubsystemJson = vi.fn(async () => {
      throw new Error('listing failed');
    });

    registerExtractionTools({
      server: registry.server,
      callSubsystemJson,
      scopeEnum,
      extractAssetTypeSchema,
      cascadeResultSchema,
      toolHelpRegistry: registry.toolHelpRegistry,
    });

    const result = await registry.getTool('list_assets').handler({
      package_path: '/Game/Missing',
      recursive: false,
      class_filter: '',
    });

    expect((result as { isError?: boolean }).isError).toBe(true);
    expect(getTextContent(result as { content?: Array<{ text?: string; type: string }> })).toContain('listing failed');
  });

  it('extract_blueprint includes StateTreeRef when component has StateTree assigned', async () => {
    const registry = createToolRegistry();
    const callSubsystemJson = vi.fn(async () => ({
      blueprint: {
        components: [{
          componentName: 'StateTree',
          componentClass: '/Script/GameplayStateTreeModule.StateTreeComponent',
          propertyOverrides: {
            bStartLogicAutomatically: false,
            'StateTreeRef.StateTree': '/Game/AI/ST_Referee.ST_Referee',
          },
        }],
      },
    }));

    registerExtractionTools({
      server: registry.server,
      callSubsystemJson,
      scopeEnum,
      extractAssetTypeSchema,
      cascadeResultSchema,
      toolHelpRegistry: registry.toolHelpRegistry,
    });

    const result = await registry.getTool('extract_blueprint').handler({
      asset_path: '/Game/Test/BP_Test',
      scope: 'Full',
      compact: false,
    });

    const parsed = parseDirectToolResult(result) as {
      blueprint: { components: Array<{ componentName: string; propertyOverrides: Record<string, unknown> }> };
    };
    const stComp = parsed.blueprint.components.find((c) => c.componentName === 'StateTree');
    expect(stComp).toBeDefined();
    expect(stComp!.propertyOverrides).toHaveProperty('StateTreeRef.StateTree');
    expect(stComp!.propertyOverrides['StateTreeRef.StateTree']).toBe('/Game/AI/ST_Referee.ST_Referee');
  });
});
