import { afterEach, describe, expect, it } from 'vitest';
import { createBlueprintExtractorServer, type UEClientLike } from '../src/index.js';
import { connectInMemoryServer, getTextContent } from './test-helpers.js';

class FakeUEClient implements UEClientLike {
  readonly calls: Array<{ method: string; params: Record<string, unknown> }> = [];

  constructor(
    private readonly handler: (method: string, params: Record<string, unknown>) => Promise<string> | string = (
      method,
      params,
    ) => JSON.stringify({ ok: true, method, params }),
  ) {}

  async callSubsystem(method: string, params: Record<string, unknown>): Promise<string> {
    this.calls.push({ method, params });
    return await this.handler(method, params);
  }
}

describe('createBlueprintExtractorServer', () => {
  const cleanups: Array<() => Promise<void>> = [];

  afterEach(async () => {
    while (cleanups.length > 0) {
      await cleanups.pop()?.();
    }
  });

  it('registers the expected resources and tools', async () => {
    const harness = await connectInMemoryServer(createBlueprintExtractorServer(new FakeUEClient()));
    cleanups.push(harness.close);

    const resources = await harness.client.listResources();
    const resourceUris = resources.resources.map((resource) => resource.uri);
    const tools = await harness.client.listTools();
    const extractBlueprint = tools.tools.find((tool) => tool.name === 'extract_blueprint');
    const createBlueprint = tools.tools.find((tool) => tool.name === 'create_blueprint');
    const saveAssets = tools.tools.find((tool) => tool.name === 'save_assets');

    expect(resourceUris).toContain('blueprint://scopes');
    expect(resourceUris).toContain('blueprint://write-capabilities');
    expect(tools.tools.some((tool) => tool.name === 'search_assets')).toBe(true);
    expect(extractBlueprint?.annotations?.readOnlyHint).toBe(true);
    expect(createBlueprint?.annotations?.readOnlyHint).toBe(false);
    expect(saveAssets?.annotations?.idempotentHint).toBe(true);
  });

  it('serves the static reference resources', async () => {
    const harness = await connectInMemoryServer(createBlueprintExtractorServer(new FakeUEClient()));
    cleanups.push(harness.close);

    const scopes = await harness.client.readResource({ uri: 'blueprint://scopes' });
    const writeCapabilities = await harness.client.readResource({ uri: 'blueprint://write-capabilities' });

    expect(scopes.contents[0]?.mimeType).toBe('text/plain');
    expect(scopes.contents[0]?.text).toContain('Blueprint Extraction Scopes');
    expect(writeCapabilities.contents[0]?.text).toContain('Current write-capable families:');
    expect(writeCapabilities.contents[0]?.text).toContain('save_assets');
  });

  it('serializes arguments to subsystem calls and returns parsed JSON', async () => {
    const fakeClient = new FakeUEClient((method, params) => JSON.stringify({
      results: [{ method, params }],
    }));
    const harness = await connectInMemoryServer(createBlueprintExtractorServer(fakeClient));
    cleanups.push(harness.close);

    const result = await harness.client.callTool({
      name: 'search_assets',
      arguments: {
        query: 'Player',
        class_filter: 'Blueprint',
        max_results: 7,
      },
    });

    expect(JSON.parse(getTextContent(result))).toEqual([
      {
        method: 'SearchAssets',
        params: {
          Query: 'Player',
          ClassFilter: 'Blueprint',
          MaxResults: 7,
        },
      },
    ]);
    expect(fakeClient.calls).toEqual([
      {
        method: 'SearchAssets',
        params: {
          Query: 'Player',
          ClassFilter: 'Blueprint',
          MaxResults: 7,
        },
      },
    ]);
  });

  it('compacts extract_blueprint responses when requested', async () => {
    const fakeClient = new FakeUEClient(() => JSON.stringify({
      blueprint: {
        functions: [{
          graphGuid: 'graph-guid',
          nodes: [{
            nodeGuid: 'guid-a',
            posX: 10,
            posY: 20,
            nodeComment: '',
            pins: [{
              pinId: 'pin-guid',
              autogeneratedDefaultValue: '',
              defaultValue: '',
              type: {
                category: 'exec',
                sub_category: '',
              },
              connections: [],
            }],
          }],
        }],
      },
    }));
    const harness = await connectInMemoryServer(createBlueprintExtractorServer(fakeClient));
    cleanups.push(harness.close);

    const result = await harness.client.callTool({
      name: 'extract_blueprint',
      arguments: {
        asset_path: '/Game/Test/BP_Test',
        compact: true,
      },
    });

    const parsed = JSON.parse(getTextContent(result));
    const node = parsed.blueprint.functions[0].nodes[0];

    expect(parsed.blueprint.functions[0].graphGuid).toBeUndefined();
    expect(node.id).toBe('n0');
    expect(node.posX).toBeUndefined();
    expect(node.posY).toBeUndefined();
    expect(node.pins[0].type).toBe('exec');
    expect(node.pins[0].connections).toBeUndefined();
  });

  it('truncates oversized extract_blueprint responses', async () => {
    const fakeClient = new FakeUEClient(() => JSON.stringify({
      blueprint: {
        summary: 'x'.repeat(220_000),
      },
    }));
    const harness = await connectInMemoryServer(createBlueprintExtractorServer(fakeClient));
    cleanups.push(harness.close);

    const result = await harness.client.callTool({
      name: 'extract_blueprint',
      arguments: {
        asset_path: '/Game/Test/BP_Large',
      },
    });

    const text = getTextContent(result);
    expect(text).toContain('Warning: Response is');
    expect(text).toContain('[TRUNCATED]');
  });

  it('returns tool errors with structured text when the subsystem returns an error JSON payload', async () => {
    const fakeClient = new FakeUEClient(() => JSON.stringify({ error: 'validation failed' }));
    const harness = await connectInMemoryServer(createBlueprintExtractorServer(fakeClient));
    cleanups.push(harness.close);

    const result = await harness.client.callTool({
      name: 'create_blueprint',
      arguments: {
        asset_path: '/Game/Test/BP_Invalid',
        parent_class_path: '/Script/Engine.Actor',
      },
    });

    expect(result.isError).toBe(true);
    expect(getTextContent(result)).toContain('validation failed');
  });

  it('surfaces schema validation failures through the MCP tool contract', async () => {
    const harness = await connectInMemoryServer(createBlueprintExtractorServer(new FakeUEClient()));
    cleanups.push(harness.close);

    const result = await harness.client.callTool({
      name: 'extract_blueprint',
      arguments: {
        asset_path: 123,
      } as never,
    });

    expect(result.isError).toBe(true);
    expect(getTextContent(result)).toContain('Input validation error');
  });
});
