import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { designSpecSchemaExample } from '../prompts/prompt-catalog.js';

function registerStaticTextResource(
  server: Pick<McpServer, 'resource'>,
  name: string,
  uri: string,
  description: string,
  lines: string[],
): void {
  server.resource(
    name,
    uri,
    { description },
    async (resourceUri) => ({
      contents: [{
        uri: resourceUri.href,
        mimeType: 'text/plain',
        text: lines.join('\n'),
      }],
    }),
  );
}

export function registerStaticDocResources(server: Pick<McpServer, 'resource'>): void {
  registerStaticTextResource(
    server,
    'extraction-scopes',
    'blueprint://scopes',
    'Reference for Blueprint extraction scopes: what each level includes, typical sizes, and when to use.',
    [
      'Blueprint Extraction Scopes',
      '',
      'Each scope includes everything from the previous level:',
      '',
      '| Scope             | Adds                                              | Typical Size  | Use When                                      |',
      '|-------------------|---------------------------------------------------|---------------|-----------------------------------------------|',
      '| ClassLevel        | Parent class, interfaces, class flags, metadata   | 1-2 KB        | Checking inheritance or interface list         |',
      '| Variables         | All variables with types, defaults, flags          | 2-10 KB       | Understanding data model (DEFAULT)             |',
      '| Components        | SCS component tree with property overrides vs CDO. For WidgetBlueprints: widget tree hierarchy with layout and bindings  | 5-20 KB       | Analyzing component composition                |',
      '| FunctionsShallow  | Function and event graph names only                | 5-25 KB       | Listing available functions before deep dive   |',
      '| Full              | Complete graph nodes, pins, and connections         | 20-500+ KB    | Understanding graph logic and execution flow   |',
      '| FullWithBytecode  | Raw bytecode hex dump per function                 | Largest        | Low-level analysis (rarely needed)             |',
      '',
      'Start with the narrowest scope that answers your question.',
      'Full scope on complex Blueprints can exceed 200KB and will be truncated.',
      '',
      'Note: Scopes only apply to Blueprint extraction (extract_blueprint and extract_cascade).',
      'DataAsset, DataTable, and StateTree always extract fully — no scope parameter is needed.',
    ],
  );

  registerStaticTextResource(
    server,
    'write-capabilities',
    'blueprint://write-capabilities',
    'Reference for explicit-save authoring workflows, write-result shape, and currently supported write-capable asset families.',
    [
      'Blueprint Extractor Write Capabilities',
      '',
      'General rules:',
      '- Write tools mutate assets in the running UE editor and return structured diagnostics.',
      '- Writes do NOT auto-save packages. Call save_assets after successful mutations you want to persist.',
      '- Write responses include: success, operation, assetPath, assetClass, changedObjects, dirtyPackages, diagnostics, and optional validation/compile summaries.',
      '',
      'Current write-capable families:',
      '- WidgetBlueprint: create_widget_blueprint, replace_widget_tree, patch_widget, insert_widget_child, remove_widget, move_widget, wrap_widget, replace_widget_class, batch_widget_operations, compile_widget. Deprecated compatibility aliases remain available for modify_widget_blueprint, build_widget_tree, and compile_widget_blueprint.',
      '- CommonUI button style Blueprints: extract_commonui_button_style, create_commonui_button_style, modify_commonui_button_style, apply_commonui_button_style',
      '- DataAsset: create_data_asset, modify_data_asset. Inline instanced UObject graphs are supported for UPROPERTY(Instanced) / EditInlineNew values.',
      '- DataTable: create_data_table, modify_data_table',
      '- Curve: create_curve, modify_curve',
      '- CurveTable: create_curve_table, modify_curve_table',
      '- Material graph assets: extract_material, create_material, modify_material, compile_material_asset. Use asset_kind="function", "layer", or "layer_blend" for material-family variants.',
      '- MaterialInstance: create_material_instance, modify_material_instance',
      '- UserDefinedStruct: create_user_defined_struct, modify_user_defined_struct',
      '- UserDefinedEnum: create_user_defined_enum, modify_user_defined_enum',
      '- Blackboard: create_blackboard, modify_blackboard',
      '- BehaviorTree: create_behavior_tree, modify_behavior_tree',
      '- StateTree: create_state_tree, modify_state_tree',
      '- AnimSequence: create_anim_sequence, modify_anim_sequence',
      '- AnimMontage: create_anim_montage, modify_anim_montage',
      '- BlendSpace: create_blend_space, modify_blend_space',
      '- Blueprint members: create_blueprint, modify_blueprint_members, modify_blueprint_graphs',
      '- Project automation context: get_project_automation_context',
      '- Shared persistence: save_assets',
      '- Host/editor orchestration: compile_project_code, trigger_live_coding, restart_editor, sync_project_code, apply_window_ui_changes',
      '',
      'Supported selectors and operation surfaces:',
      '- UserDefinedStruct: field selector by guid or name; operations replace_fields, patch_field, rename_field, remove_field, reorder_fields.',
      '- UserDefinedEnum: entry selector by name; operations replace_entries, rename_entry, remove_entry, reorder_entries.',
      '- Blackboard: key selector by entryName; operations replace_keys, patch_key, remove_key, set_parent.',
      '- BehaviorTree: node selector by nodePath; operations replace_tree, patch_node, patch_attachment, set_blackboard.',
      '- StateTree: selectors by stateId/statePath, editorNodeId, or transitionId; operations replace_tree, patch_state, patch_editor_node, patch_transition, set_schema, set_bindings, add_binding, remove_binding. Blueprint-wrapped nodes (StateTreeBlueprintTaskWrapper / StateTreeBlueprintConditionWrapper) require instanceObjectClass for the backing instance to exist at runtime.',
      '- StateTree property bindings wire task/evaluator outputs to task inputs. Use extract_asset to discover structIds and property names. Each binding has sourcePath and targetPath with segments: [{name, arrayIndex?, instanceStruct?}] and optional structId. Operations: set_bindings (replace all), add_binding (append), remove_binding (by targetPath). In replace_tree/create: include as { bindings: { propertyBindings: [...] } }.',
      '- AnimSequence: notify selector by notifyId/notifyGuid with notifyIndex or track metadata as fallback; operations replace_notifies, patch_notify, replace_sync_markers, replace_curve_metadata.',
      '- AnimMontage: notify selector by notifyId/notifyGuid with notifyIndex or track metadata as fallback; operations replace_notifies, patch_notify, replace_sections, replace_slots.',
      '- BlendSpace: sample selector by sampleIndex; operations replace_samples, patch_sample, set_axes.',
      '- Blueprint members: selectors by variableName, componentName, and functionName; operations replace_variables, patch_variable, replace_components, patch_component, add_component, replace_function_stubs, reparent, patch_class_defaults, compile. Reparenting uses payload.parentClassPath, and payload.parent_class_path is accepted as an alias.',
      '- Blueprint graphs: operation upsert_function_graphs preserves unrelated graphs; append_function_call_to_sequence patches an existing sequence-style initializer without replacing the whole graph.',
      '',
      'WidgetBlueprint guidance:',
      '- replace_widget_tree is the destructive bootstrap path for whole-tree replacement.',
      '- extract_widget_blueprint returns a compact authoring snapshot with widgetPath annotations and additive packagePath/objectPath fields.',
      '- modify_widget supports direct widget_name or widget_path patches for one widget.',
      '- Prefer operation-specific widget tools such as patch_widget, patch_widget_class_defaults, insert_widget_child, remove_widget, move_widget, wrap_widget, replace_widget_class, and batch_widget_operations.',
      '- compile_widget validates the asset but still does not save it.',
      '- apply_window_ui_changes is a thin MCP helper that sequences variable-flag updates, class defaults, optional font work, compile, optional save, and optional code sync.',
      '',
      'Explicit deferrals:',
      '- Blueprint graph authoring is explicit and opt-in via modify_blueprint_graphs; generic arbitrary graph synthesis is still intentionally bounded to targeted graph operations.',
      '- Material graph authoring currently targets the classic material ecosystem; there is no first-class Substrate-specific DSL yet.',
      '- No ControlRig, IK controller, or live world editing surfaces.',
      '- Animation authoring is limited to metadata, sections, slots, samples, notifies, sync markers, and curve metadata; raw authored track synthesis is out of scope.',
    ],
  );

  registerStaticTextResource(
    server,
    'import-capabilities',
    'blueprint://import-capabilities',
    'Reference for async asset import payloads, job polling, status fields, and specialized texture or mesh option keys.',
    [
      'Blueprint Extractor Import Capabilities',
      '',
      'General rules:',
      '- Import tools enqueue async jobs in the running UE editor and return a job status object immediately.',
      '- Poll get_import_job with the returned jobId until terminal=true, or use list_import_jobs to inspect multiple jobs.',
      '- Import responses do NOT auto-save packages. Call save_assets after a successful terminal job if you want packages persisted.',
      '- Import payloads are passed through as subsystem JSON with an items array. The MCP layer preserves snake_case field names.',
      '',
      'Shared item fields:',
      '- file_path or url: exactly one source per item.',
      '- filename: optional suggested filename for URL sources.',
      '- headers: optional string map for URL downloads.',
      '- destination_path: target package path such as /Game/Imported.',
      '- destination_name: optional asset name override.',
      '- asset_path: optional explicit object path.',
      '- replace_existing, replace_existing_settings: optional overwrite flags.',
      '',
      'Texture item options:',
      '- compression_settings, lod_group, s_rgb/srgb, virtual_texture_streaming, flip_green_channel.',
      '',
      'Mesh item options:',
      '- mesh_type: "static" or "skeletal".',
      '- import_materials, import_textures, import_animations, combine_meshes, generate_collision.',
      '- skeleton_path is required for skeletal mesh imports.',
      '',
      'Job status payload fields:',
      '- success, operation, status, terminal, validateOnly, createdAt, startedAt, completedAt, jobId.',
      '- itemCount, acceptedItemCount, failedItemCount, importedObjects, dirtyPackages, diagnostics.',
      '- items[] entries include index, status, source path/url, destination info, importedObjects, dirtyPackages, and diagnostics.',
      '',
      'Known status values:',
      '- Job: queued, running, succeeded, partial_success, failed.',
      '- Item: queued, downloading, staged, importing, succeeded, failed.',
    ],
  );

  registerStaticTextResource(
    server,
    'authoring-conventions',
    'blueprint://authoring-conventions',
    'Short reference for explicit-save write flows, validate_only behavior, and compact authoring habits.',
    [
      'Blueprint Extractor Authoring Conventions',
      '',
      '- Prefer validate_only=true before the first write to a new asset family or payload shape.',
      '- Writes mutate the live editor but do not save automatically; call save_assets when you want disk persistence.',
      '- Use the narrowest mutation tool that fits: patch one widget/member first, replace whole trees only when structure is changing broadly.',
      '- Keep payloads small by sending only changed fields, not full extracted objects, unless the tool explicitly expects a full replacement payload.',
      '- Re-extract after mutation when you need confirmation; do not assume UE normalized fields exactly as sent.',
      '- For fidelity-sensitive menu work, normalize text, image, Figma-export, or HTML/CSS inputs into design_spec_json before authoring assets.',
      '- For multi-step widget work, prefer extract_widget_blueprint -> patch_widget or batch_widget_operations -> compile_widget -> capture_widget_preview -> save_assets.',
      '- For authored widget motion, prefer extract_widget_animation -> create_widget_animation or modify_widget_animation -> capture_widget_motion_checkpoints -> compare_motion_capture_bundle before save_assets.',
      '- When reference frames exist, extend the widget flow to compare_capture_to_reference before save_assets. Without reference frames, capture and report lower-confidence or partial verification explicitly.',
      '- If widget preview capture is blocked, report partial verification explicitly instead of treating compile/save as visual proof.',
      '- For code orchestration, pass explicit changed_paths to sync_project_code instead of relying on source-control inference.',
    ],
  );

  registerStaticTextResource(
    server,
    'selector-conventions',
    'blueprint://selector-conventions',
    'Selector naming and addressing conventions across write-capable families.',
    [
      'Blueprint Extractor Selector Conventions',
      '',
      '- WidgetBlueprints: use widget_path for nested widgets when practical; use widget_name for flat or unique-tree edits.',
      '- Widget animation tracks and bindings: use widget_path as the canonical selector; only fall back to widget_name when the target widget is unambiguous.',
      '- BehaviorTree: use nodePath.',
      '- StateTree: use statePath/stateId, editorNodeId, or transitionId.',
      '- Blueprint members: use variableName, componentName, and functionName.',
      '- Anim assets: prefer stable notifyId/notifyGuid and sampleIndex selectors over array-position assumptions.',
      '- When a tool supports both name and path selectors, path is the safer choice after structural edits.',
      '- Public MCP inputs use one canonical snake_case shape. Do not rely on legacy aliases.',
      '- sync_project_code requires explicit changed_paths; it does not infer them from source control state.',
    ],
  );

  registerStaticTextResource(
    server,
    'widget-best-practices',
    'blueprint://widget-best-practices',
    'UE/CommonUI-focused widget authoring guidance for Claude/Codex-driven Blueprint creation.',
    [
      'Blueprint Extractor Widget Best Practices',
      '',
      '- C++ owns widget logic and BindWidget fields; Blueprint owns layout and styling.',
      '- Use concrete widget classes in trees. Do not instantiate abstract bases such as UserWidget or CommonButtonBase.',
      '- Prefer CommonActivatableWidget as the root parent for CommonUI screens and windows.',
      '- Prefer VerticalBox, HorizontalBox, Overlay, Border, SizeBox, ScrollBox, and NamedSlot over CanvasPanel unless absolute positioning is required.',
      '- Keep styling centralized. Reuse fonts, colors, and button classes instead of repeating large inline property blobs.',
      '- Build reusable menu foundation assets under /Game/UI/Foundation/Materials, /Game/UI/Foundation/MaterialInstances, /Game/UI/Foundation/Styles, and /Game/UI/Foundation/Widgets instead of styling each screen from scratch.',
      '- CommonButtonBase is not a raw UButton surface. Do not target UButton background/style fields through patch_class_defaults or patch_widget on CommonUI wrappers; use extract_commonui_button_style, create_commonui_button_style, modify_commonui_button_style, and apply_commonui_button_style instead.',
      '- When extract_widget_blueprint reports rootWidget=null, inspect widgetTreeStatus, widgetTreeError, and compile.errors before attempting structural rewrites. A degraded snapshot is still useful for recovery.',
      '- WidthOverride, HeightOverride, MinDesiredHeight, and similar fields may require paired bOverride_* flags. The write path now enables those flags automatically, but re-extract after patching to confirm the authored value landed where expected.',
      '- For long multi-step UI flows, use apply_window_ui_changes.checkpoint_after_mutation_steps=true so later compile/debug interruptions do not discard earlier successful edits.',
      '- For user-facing widget changes, compile/save is not the terminal checkpoint. Finish with capture_widget_preview or return partial verification with the blocking reason.',
      '- Use create_widget_animation and modify_widget_animation for authored UI motion on the supported track subset: render_opacity, render_transform_translation, render_transform_scale, render_transform_angle, and color_and_opacity.',
      '- Use widget_path selectors for animation bindings, keep replace_timeline as the default mutation style, and persist checkpoints as named frames so verification can reuse them.',
      '- Only mark motion work deferred_to_future when it exceeds the supported track subset or requires broader arbitrary MovieScene synthesis.',
      '- Prefer event-driven updates and explicit setter functions over heavy property bindings or per-frame tick work.',
      '- Use TSubclassOf + CreateWidget only for truly dynamic repeated elements. Keep authored static layout in the Widget Blueprint tree.',
    ],
  );

  registerStaticTextResource(
    server,
    'material-graph-guidance',
    'blueprint://material-graph-guidance',
    'Classic material graph guidance for materials, functions, layers, blends, and instance parity.',
    [
      'Blueprint Extractor Material Graph Guidance',
      '',
      'Supported assets:',
      '- UMaterial',
      '- UMaterialFunction',
      '- UMaterialFunctionMaterialLayer',
      '- UMaterialFunctionMaterialLayerBlend',
      '- UMaterialInstanceConstant parity via create_material_instance / modify_material_instance',
      '',
      'Stable selectors:',
      '- Expressions use expression_guid.',
      '- New expressions may be referenced within one batch by temp_id, then read back from tempIdMap.',
      '- Material root properties use engine enum names such as MP_BaseColor, MP_Normal, and MP_EmissiveColor.',
      '',
      'Primary operations:',
      '- add_expression, duplicate_expression, delete_expression, set_expression_properties, move_expression',
      '- connect_expressions, disconnect_expression_input',
      '- connect_material_property, disconnect_material_property',
      '- add_comment, delete_comment',
      '- rename_parameter_group, set_material_settings, set_layer_stack',
      '',
      'Defaults:',
      '- Extraction is compact by default; set verbose=true only when you need more authored property detail.',
      '- Mutations compile after apply unless compile_after=false.',
      '- Writes do not save packages automatically; call save_assets after successful mutations.',
      '',
      'Current limits:',
      '- No first-class Substrate authoring DSL yet. Substrate nodes still extract as generic expressions.',
      '- MaterialFunction assets use FunctionInput and FunctionOutput nodes as graph entry/exit points instead of material root-property bindings.',
    ],
  );

  registerStaticTextResource(
    server,
    'font-role-guidance',
    'blueprint://font-roles',
    'Compact UI font-role guidance for project-owned runtime fonts and widget application payloads.',
    [
      'Blueprint Extractor Font Roles',
      '',
      '- Use explicit font file paths as the stable import contract; do not rely on installed-font name lookup.',
      '- Import project-owned UFontFace assets, then optionally synthesize/update a runtime UFont for widget use.',
      '- Apply fonts to widgets through compact payloads: widget selector + font_asset + typeface + size.',
      '',
      'Suggested roles:',
      '- title: typeface=Bold, size=18-24',
      '- button: typeface=Bold or Semibold, size=12-16',
      '- body: typeface=Regular, size=10-14',
      '- caption: typeface=Regular, size=9-11',
      '',
      'Keep font styling centralized in shared assets instead of repeating large FSlateFontInfo blobs.',
    ],
  );

  registerStaticTextResource(
    server,
    'project-automation-guidance',
    'blueprint://project-automation',
    'Host/editor project automation guidance for build, Live Coding, restart, and reconnect flows.',
    [
      'Blueprint Extractor Project Automation',
      '',
      '- get_project_automation_context returns the editor-derived engine root, project file path, editor target, and isPlayingInEditor state that project-control tools use as their first fallback.',
      '- compile_project_code runs an external UBT build from the MCP host.',
      '- compile_project_code and sync_project_code resolve engine_root, project_path, and target in this order: explicit args -> editor context -> environment.',
      '- trigger_live_coding requests an editor-side Live Coding compile and is only supported on Windows-focused setups. changed_paths remains an accepted compatibility input but the current editor-side trigger ignores it. When Live Coding reports NoChanges or another fallback state, the result includes fallbackRecommended, reason, and the last external build context when available.',
      '- restart_editor requests an editor restart, then waits for Remote Control to disconnect and reconnect. When save_dirty_assets is true, all dirty packages are saved before the restart to prevent modal save dialogs.',
      '- wait_for_editor polls Remote Control once per second and returns a normalized readiness result that callers can use after restart windows or transient disconnects.',
      '- start_pie, stop_pie, and relaunch_pie are the explicit live-editor PIE lifecycle controls.',
      '- sync_project_code requires explicit changed_paths and chooses Live Coding vs build_and_restart deterministically.',
      '- sync_project_code.restart_first now means shutdown-first: save/checkpoint if requested, ask the editor to close without relaunching, build with the DLL unlocked, then launch the editor from the MCP host and wait for reconnect.',
      '- apply_window_ui_changes can checkpoint after each mutation step without changing the low-level explicit-save contract. Use that when debugging editor ensures or breakpoint-heavy UI iterations.',
      '',
      'build_and_restart is forced for:',
      '- .h/.hpp/.inl/.generated.h changes',
      '- .Build.cs, .Target.cs, .uplugin, .uproject changes',
      '- explicit force_rebuild=true',
      '',
      'Generic Live Coding Failure is not auto-promoted into a rebuild. The caller receives the failure result directly.',
    ],
  );

  registerStaticTextResource(
    server,
    'verification-workflows',
    'blueprint://verification-workflows',
    'Verification guidance mapping semantic, visual, and gameplay/runtime changes to the right verification lane.',
    [
      'Blueprint Extractor Verification Workflows',
      '',
      'Three verification lanes work together:',
      '- Semantic verification: use extract_blueprint, extract_widget_blueprint, extract_asset, compile_widget, compile_material_asset, and compile/save diagnostics to verify authored data, graph wiring, widget hierarchy, class defaults, and graph layout.',
      '- Visual verification: use capture_widget_preview, capture_editor_screenshot, capture_runtime_screenshot, and compare_capture_to_reference when structure can compile but the rendered result may still be wrong.',
      '- Gameplay/runtime verification: use run_automation_tests for mechanics, behavior, interactions, and scenario validation through Automation Specs or Functional Tests.',
      '',
      'Recommended mapping:',
      '- Blueprint graph or member changes: semantic first.',
      '- Widget structure, slot layout, class defaults: semantic first, then visual if the change is user-facing.',
      '- High-fidelity menu design: normalize raw inputs into design_spec_json, verify checkpoints visually, and compare against reference frames when they exist.',
      '- Authored widget motion: extract or patch the animation, capture keyframe bundles with capture_widget_motion_checkpoints, then compare checkpoints with compare_motion_capture_bundle or compare_capture_to_reference.',
      '- Data assets, tables, AI trees, input assets: semantic verification through extractors and compile diagnostics.',
      '- Gameplay mechanics, scripted interactions, runtime flows: automation tests first.',
      '',
      'Guardrail:',
      '- User-facing widget work is not complete until capture_widget_preview succeeds or the response explicitly reports partial verification with a blocking reason.',
      '- If reference images or checkpoint frames exist, use compare_capture_to_reference or compare_motion_capture_bundle for key states such as open, focused, or pressed. Without those references, capture the state and report lower-confidence or partial verification when fidelity is uncertain.',
      '- Motion verification is checkpoint-bundle based. Menu/shell widgets should prefer editor_preview playback, while HUD/runtime flows should prefer automation_scenario playback and named checkpoint artifacts.',
      '- Compile/save alone is never accepted as motion verification. If a requested track family exceeds the supported widget-animation subset, return a structured partial implementation / deferred_to_future boundary instead of pretending the timeline exists.',
      '- If no Automation Spec or Functional Test exists for a gameplay mechanic, report verification as partial instead of inferring success from structure or screenshots alone.',
    ],
  );

  registerStaticTextResource(
    server,
    'design-spec-schema',
    'blueprint://design-spec-schema',
    'Compact schema and example payload for the shared multimodal menu design_spec_json contract.',
    [
      'Blueprint Extractor Design Spec Schema',
      '',
      'Use design_spec_json as the shared contract between multimodal design intake and Unreal authoring.',
      '',
      'Required top-level blocks:',
      '- layout',
      '- visual_tokens',
      '- components',
      '',
      'Optional top-level blocks:',
      '- motion',
      '- verification',
      '',
      'JSON example:',
      JSON.stringify(designSpecSchemaExample, null, 2),
    ],
  );

  registerStaticTextResource(
    server,
    'multimodal-ui-design-workflow',
    'blueprint://multimodal-ui-design-workflow',
    'Canonical multimodal, reference-driven menu workflow with first-class widget motion authoring and checkpoint verification.',
    [
      'Blueprint Extractor Multimodal UI Design Workflow',
      '',
      'Input priority:',
      '- text+image and PNG/Figma are first-class high-fidelity references.',
      '- HTML/CSS is near-parity when you extract tokens and compare against rendered reference frames instead of assuming direct DOM-to-UMG translation.',
      '- text-only is supported, but it remains a lower-confidence path when no visual references exist.',
      '',
      'Canonical flow:',
      '1. Normalize raw text, image, PNG/Figma, or HTML/CSS inputs into design_spec_json.',
      '2. Inspect the current widget, HUD, transition widgets, and class defaults before rewriting structure.',
      '3. Author reusable foundation assets first under /Game/UI/Foundation/Materials, /Game/UI/Foundation/MaterialInstances, /Game/UI/Foundation/Styles, and /Game/UI/Foundation/Widgets.',
      '4. Assemble the menu screen under /Game/UI/Screens with patch_widget, batch_widget_operations, and related widget tools.',
      '5. If motion is part of the spec, author or patch widget timelines with create_widget_animation or modify_widget_animation using the supported track subset.',
      '6. Compile, then capture key visual checkpoints such as open, focused, or pressed.',
      '7. If reference frames exist, compare captures with compare_capture_to_reference or compare_motion_capture_bundle before save_assets.',
      '8. If reference frames do not exist, capture the result and report lower-confidence or partial verification explicitly when fidelity is uncertain.',
      '',
      'Motion policy:',
      '- V2 adds dedicated widget-animation authoring for render_opacity, render_transform_translation, render_transform_scale, render_transform_angle, and color_and_opacity.',
      '- Prefer widget_path selectors, replace_timeline payloads, named checkpoints, and compareable keyframe bundles over ad-hoc manual authoring.',
      '- Use static checkpoints for motion verification: closed, opening_peak, open, focused, pressed, or project-specific equivalents.',
      '- If the requested motion requires unsupported track families or broader arbitrary MovieScene synthesis, mark only that portion deferred_to_future / partial implementation.',
    ],
  );

  registerStaticTextResource(
    server,
    'widget-motion-authoring',
    'blueprint://widget-motion-authoring',
    'Widget animation authoring guidance for the dedicated widget animation tools and supported track subset.',
    [
      'Blueprint Extractor Widget Motion Authoring',
      '',
      'Primary tools:',
      '- extract_widget_animation for deep timeline, binding, playback, and checkpoint inspection.',
      '- create_widget_animation to create a named animation on an existing WidgetBlueprint.',
      '- modify_widget_animation to replace timelines, patch metadata, rename, remove, or compile an animation.',
      '',
      'Authoring rules:',
      '- extract_widget_blueprint.animations remains the shallow inventory surface; use extract_widget_animation when you need binding targets, checkpoints, or authored keys.',
      '- Use widget_path as the canonical selector for animation bindings and track targets. Use widget_name only as a compatibility fallback when unique.',
      '- The initial supported track subset is explicit: render_opacity, render_transform_translation, render_transform_scale, render_transform_angle, and color_and_opacity.',
      '- Use replace_timeline as the default write path. Prefer whole-track replacement over fine-grained key patching in the initial release.',
      '- patch_metadata is for display labels, checkpoints, playback metadata, and similar non-track updates. It is not a generic key-edit API.',
      '- Persist checkpoints as named frames so capture_widget_motion_checkpoints can reuse them without guessing.',
      '- If the requested motion exceeds the supported track subset, return a structured partial implementation / deferred_to_future boundary instead of synthesizing unsupported tracks.',
    ],
  );

  registerStaticTextResource(
    server,
    'motion-verification-workflow',
    'blueprint://motion-verification-workflow',
    'Keyframe-bundle verification guidance for menu/shell widget motion and HUD/runtime playback.',
    [
      'Blueprint Extractor Motion Verification Workflow',
      '',
      'Primary tools:',
      '- capture_widget_motion_checkpoints returns a keyframe bundle with verificationArtifacts for each named checkpoint.',
      '- compare_motion_capture_bundle compares a captured bundle against reference frames or another bundle checkpoint-by-checkpoint.',
      '',
      'Modes:',
      '- editor_preview: use for menu shells and authored WidgetBlueprint animations when editor playback is sufficient.',
      '- automation_scenario: use for HUD/runtime flows that require gameplay or scripted scenario playback through run_automation_tests.',
      '',
      'Canonical checkpoints:',
      '- closed',
      '- opening_peak',
      '- open',
      '- focused',
      '- pressed',
      '',
      'Verification rules:',
      '- Verification output is a keyframe bundle, not video or GIF.',
      '- Menu/shell motion should prefer editor_preview when the authored widget animation is the source of truth.',
      '- HUD/runtime motion should prefer automation_scenario and named checkpoint artifact export. Do not imply that editor preview proves runtime behavior.',
      '- When reference frames exist, compare them with compare_motion_capture_bundle or compare_capture_to_reference before save_assets.',
      '- When a scenario cannot export checkpoint artifacts yet, report partial verification explicitly instead of silently treating the automation run as sufficient proof.',
      '- Compile/save alone is never accepted as motion verification.',
    ],
  );

  registerStaticTextResource(
    server,
    'analysis-workflows',
    'blueprint://analysis-workflows',
    'Job-based entry paths for deterministic Blueprint review and asset-audit workflows.',
    [
      'Blueprint Extractor Analysis Workflows',
      '',
      'Understand project:',
      '- refresh_project_index -> get_project_index_status -> search_project_context',
      '',
      'Review asset:',
      '- review_blueprint -> extract_blueprint',
      '- review_blueprint returns deterministic findings only. Each finding includes severity, category, evidence, and next_steps.',
      '',
      'Audit project:',
      '- audit_project_assets for low-noise asset metadata checks.',
      '- Current check families: naming, package hygiene, and asset-family coverage.',
      '',
      'Guardrail:',
      '- Findings-first output is intentional. Do not treat review_blueprint or audit_project_assets as autofix tools.',
    ],
  );

  registerStaticTextResource(
    server,
    'project-intelligence-workflows',
    'blueprint://project-intelligence-workflows',
    'Job-based entry paths for indexing/searching published context and snapshotting bounded editor context.',
    [
      'Blueprint Extractor Project Intelligence Workflows',
      '',
      'Project indexing:',
      '- refresh_project_index caches asset metadata plus published docs, prompts, and resources.',
      '- get_project_index_status reports freshness, size, and staleness.',
      '- search_project_context returns snippet-first results with provenance and pagination.',
      '',
      'Snapshot editor context:',
      '- get_editor_context is bounded, session-bound, and read-only.',
      '- Returned sections are intentionally limited: selected_asset_paths, selected_actor_names, open_asset_editors, active_level, and pie_summary.',
      '',
      'Unsupported boundaries:',
      '- get_editor_context does not open assets, change editor focus, or switch viewports.',
      '- Search remains metadata-first in v1; code indexing is intentionally deferred.',
    ],
  );
}
