/**
 * Compacts Blueprint extraction JSON by stripping low-value fields and minifying.
 * Reduces size by ~50-70% for LLM consumption.
 */

type AnyObject = Record<string, unknown>;

/**
 * Compacts a parsed Blueprint extraction result.
 * - Removes positional data (posX, posY), GUIDs, empty fields
 * - Replaces nodeGuid with sequential short IDs (n0, n1, ...)
 * - Rewrites connection references to use short IDs
 * - Replaces exec pin type objects with the string "exec"
 */
export function compactBlueprint(data: unknown): unknown {
  if (!data || typeof data !== 'object') return data;
  const root = data as AnyObject;

  const bp = root.blueprint as AnyObject | undefined;
  if (!bp) return data;

  // Branch 1: Compact graphs (if present)
  const functions = bp.functions as AnyObject[] | undefined;
  if (Array.isArray(functions)) {
    for (const graph of functions) {
      compactGraph(graph);
    }
  }

  // Branch 2: Compact widget tree (if present)
  const wt = bp.widgetTree as AnyObject | undefined;
  if (wt && typeof wt === 'object' && wt.rootWidget) {
    compactWidgetNode(wt.rootWidget as AnyObject);
  }

  return data;
}

function compactGraph(graph: AnyObject): void {
  // Remove graphGuid at graph level
  delete graph.graphGuid;

  const nodes = graph.nodes as AnyObject[] | undefined;
  if (!Array.isArray(nodes)) return;

  // Build guidToShortId map
  const guidToShortId = new Map<string, string>();
  for (let i = 0; i < nodes.length; i++) {
    const guid = nodes[i].nodeGuid as string | undefined;
    if (guid) {
      guidToShortId.set(guid, `n${i}`);
    }
  }

  // Process each node
  for (let i = 0; i < nodes.length; i++) {
    const node = nodes[i];

    // Replace nodeGuid with short ID
    delete node.nodeGuid;
    node.id = `n${i}`;

    // Remove positional data
    delete node.posX;
    delete node.posY;

    // Remove empty nodeComment
    if (node.nodeComment === '') {
      delete node.nodeComment;
    }

    // Process pins
    const pins = node.pins as AnyObject[] | undefined;
    if (Array.isArray(pins)) {
      for (const pin of pins) {
        compactPin(pin, guidToShortId);
      }
    }
  }
}

function compactWidgetNode(node: AnyObject): void {
  if (!node) return;

  // Remove displayLabel when it equals name or is empty (redundant)
  if (node.displayLabel === node.name || node.displayLabel === '') {
    delete node.displayLabel;
  }

  // Remove default visibility
  if (node.visibility === 'Visible') {
    delete node.visibility;
  }

  // Remove empty properties objects
  if (node.properties && typeof node.properties === 'object' && Object.keys(node.properties as object).length === 0) {
    delete node.properties;
  }

  // Recurse into children
  const children = node.children as AnyObject[] | undefined;
  if (Array.isArray(children)) {
    for (const child of children) {
      compactWidgetNode(child);
    }
  }
}

function compactPin(pin: AnyObject, guidToShortId: Map<string, string>): void {
  // Remove pinId
  delete pin.pinId;

  // Remove autogeneratedDefaultValue
  delete pin.autogeneratedDefaultValue;

  // Remove empty defaultValue
  if (pin.defaultValue === '') {
    delete pin.defaultValue;
  }

  // Process type object
  const type = pin.type as AnyObject | undefined;
  if (type && typeof type === 'object') {
    // Remove empty sub_category
    if (type.sub_category === '') {
      delete type.sub_category;
    }

    // Replace exec pin type with string "exec"
    if (type.category === 'exec') {
      pin.type = 'exec';
    }
  }

  // Rewrite connection nodeGuid references to short IDs
  const connections = pin.connections as AnyObject[] | undefined;
  if (Array.isArray(connections)) {
    if (connections.length === 0) {
      // Remove empty connections arrays
      delete pin.connections;
    } else {
      for (const conn of connections) {
        const connGuid = conn.nodeGuid as string | undefined;
        if (connGuid && guidToShortId.has(connGuid)) {
          conn.nodeGuid = guidToShortId.get(connGuid);
        }
      }
    }
  }
}
