#!/usr/bin/env node
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';
import { UEClient } from './ue-client.js';
import { compactBlueprint } from './compactor.js';

const client = new UEClient();

const server = new McpServer({
  name: 'blueprint-extractor',
  version: '1.3.0',
});

// Shared scope enum with detailed descriptions
const scopeEnum = z.enum([
  'ClassLevel',
  'Variables',
  'Components',
  'FunctionsShallow',
  'Full',
  'FullWithBytecode',
]);

// Resource: extraction scope reference (static docs — app-controlled read-only context)
server.resource(
  'extraction-scopes',
  'blueprint://scopes',
  {
    description: 'Reference for Blueprint extraction scopes: what each level includes, typical sizes, and when to use.',
  },
  async (uri) => ({
    contents: [{
      uri: uri.href,
      mimeType: 'text/plain',
      text: [
        'Blueprint Extraction Scopes',
        '',
        'Each scope includes everything from the previous level:',
        '',
        '| Scope             | Adds                                              | Typical Size  | Use When                                      |',
        '|-------------------|---------------------------------------------------|---------------|-----------------------------------------------|',
        '| ClassLevel        | Parent class, interfaces, class flags, metadata   | 1-2 KB        | Checking inheritance or interface list         |',
        '| Variables         | All variables with types, defaults, flags          | 2-10 KB       | Understanding data model (DEFAULT)             |',
        '| Components        | SCS component tree with property overrides vs CDO  | 5-20 KB       | Analyzing component composition                |',
        '| FunctionsShallow  | Function and event graph names only                | 5-25 KB       | Listing available functions before deep dive   |',
        '| Full              | Complete graph nodes, pins, and connections         | 20-500+ KB    | Understanding graph logic and execution flow   |',
        '| FullWithBytecode  | Raw bytecode hex dump per function                 | Largest        | Low-level analysis (rarely needed)             |',
        '',
        'Start with the narrowest scope that answers your question.',
        'Full scope on complex Blueprints can exceed 200KB and will be truncated.',
        '',
        'Note: Scopes only apply to Blueprint extraction (extract_blueprint and extract_cascade).',
        'DataAsset, DataTable, and StateTree always extract fully — no scope parameter is needed.',
      ].join('\n'),
    }],
  }),
);

// Tool 1: extract_blueprint
server.registerTool(
  'extract_blueprint',
  {
    title: 'Extract Blueprint',
    description: `Extract a UE5 Blueprint asset to structured JSON.

USAGE GUIDELINES:
- Use search_assets first to find the correct asset path if you don't already have it.
- Start with the narrowest scope that answers your question — each level includes everything from the previous:
  * ClassLevel — parent class, interfaces, class flags, metadata (~1-2KB)
  * Variables — + all variables with types, defaults, flags (~2-10KB)
  * Components — + SCS component tree with property overrides (~5-20KB)
  * FunctionsShallow — + function/event graph names only (~5-25KB)
  * Full — + complete graph nodes, pins, and connections (~20-500KB+)
  * FullWithBytecode — + raw bytecode hex dump (largest, rarely needed)
- Only escalate to Full when you need to understand graph logic (node connections, pin values, execution flow).
- Full scope on complex Blueprints can exceed 200KB and will be truncated. If truncated, use a narrower scope or inspect specific functions via the graph names from FunctionsShallow.
- Use FunctionsShallow scope first to get graph names, then request specific graphs with graph_filter to reduce output size.
- Use compact=true to reduce JSON size by ~50-70% for LLM consumption.

RETURNS: JSON object with the extracted Blueprint data at the requested scope level.`,
    inputSchema: {
      asset_path: z.string().describe(
        'UE content path to the Blueprint asset. Must start with /Game/ (e.g. /Game/Blueprints/BP_Character). Use search_assets to find paths.',
      ),
      scope: scopeEnum.default('Variables').describe(
        'Extraction depth. Start with ClassLevel or Variables — only use Full when you need graph/node details.',
      ),
      graph_filter: z.array(z.string()).optional().describe(
        'Filter to specific graphs by name. Use FunctionsShallow scope first to discover graph names, then pass the names you want here. Empty/omitted = extract all graphs. Example: ["EventGraph", "CalculateDamage"]',
      ),
      compact: z.boolean().default(false).describe(
        'When true, strips low-value fields and minifies JSON to reduce size by ~50-70%. Removes: pinId, posX/posY, graphGuid, autogeneratedDefaultValue, nodeComment (when empty), empty connections, empty default_value, empty sub_category. Replaces full exec pin type objects with the string "exec".',
      ),
    },
    annotations: {
      title: 'Extract Blueprint',
      readOnlyHint: true,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: false,
    },
  },
  async ({ asset_path, scope, graph_filter, compact }) => {
    try {
      const result = await client.callSubsystem('ExtractBlueprint', {
        AssetPath: asset_path,
        Scope: scope,
        GraphFilter: graph_filter ? graph_filter.join(',') : '',
      });
      let parsed = JSON.parse(result);
      if (parsed.error) {
        return { content: [{ type: 'text' as const, text: `Error: ${parsed.error}` }], isError: true };
      }
      if (compact) {
        parsed = compactBlueprint(parsed);
      }
      const text = compact ? JSON.stringify(parsed) : JSON.stringify(parsed, null, 2);
      if (text.length > 200_000) {
        return { content: [{ type: 'text' as const, text: `Warning: Response is ${(text.length / 1024).toFixed(0)}KB — consider using a narrower scope (ClassLevel, Variables, or FunctionsShallow).\n\n${text.substring(0, 200_000)}...\n[TRUNCATED]` }] };
      }
      return { content: [{ type: 'text' as const, text }] };
    } catch (e) {
      return { content: [{ type: 'text' as const, text: `Error: ${e instanceof Error ? e.message : String(e)}` }], isError: true };
    }
  },
);

// Tool 2: extract_statetree
server.registerTool(
  'extract_statetree',
  {
    title: 'Extract StateTree',
    description: `Extract a UE5 StateTree asset to structured JSON.

USAGE GUIDELINES:
- Use search_assets first to find the asset path if needed (filter by class "StateTree").
- Returns the full state hierarchy: states, tasks, conditions, transitions, evaluators, and linked assets.
- Response size depends on StateTree complexity — typically 10-100KB.

RETURNS: JSON object with schema, state hierarchy, tasks, conditions, transitions, and linked assets.`,
    inputSchema: {
      asset_path: z.string().describe(
        'UE content path to a StateTree asset (e.g. /Game/AI/ST_BotBehavior). Use search_assets with class_filter "StateTree" to find paths.',
      ),
    },
    annotations: {
      title: 'Extract StateTree',
      readOnlyHint: true,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: false,
    },
  },
  async ({ asset_path }) => {
    try {
      const result = await client.callSubsystem('ExtractStateTree', { AssetPath: asset_path });
      const parsed = JSON.parse(result);
      if (parsed.error) {
        return { content: [{ type: 'text' as const, text: `Error: ${parsed.error}` }], isError: true };
      }
      return { content: [{ type: 'text' as const, text: JSON.stringify(parsed, null, 2) }] };
    } catch (e) {
      return { content: [{ type: 'text' as const, text: `Error: ${e instanceof Error ? e.message : String(e)}` }], isError: true };
    }
  },
);

// Tool 3: extract_dataasset
server.registerTool(
  'extract_dataasset',
  {
    title: 'Extract DataAsset',
    description: `Extract a UE5 DataAsset to structured JSON. Serializes all user-defined UPROPERTY fields using UE reflection.

USAGE GUIDELINES:
- Use search_assets first with class_filter "DataAsset" or a specific DataAsset subclass name to find the asset path.
- Returns all user-defined properties with their types and current values.
- Works with any UDataAsset or UPrimaryDataAsset subclass.

RETURNS: JSON object with the DataAsset's class info and all property values.`,
    inputSchema: {
      asset_path: z.string().describe(
        'UE content path to the DataAsset (e.g. /Game/Data/DA_ItemDatabase). Use search_assets to find paths.',
      ),
    },
    annotations: {
      title: 'Extract DataAsset',
      readOnlyHint: true,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: false,
    },
  },
  async ({ asset_path }) => {
    try {
      const result = await client.callSubsystem('ExtractDataAsset', { AssetPath: asset_path });
      const parsed = JSON.parse(result);
      if (parsed.error) {
        return { content: [{ type: 'text' as const, text: `Error: ${parsed.error}` }], isError: true };
      }
      return { content: [{ type: 'text' as const, text: JSON.stringify(parsed, null, 2) }] };
    } catch (e) {
      return { content: [{ type: 'text' as const, text: `Error: ${e instanceof Error ? e.message : String(e)}` }], isError: true };
    }
  },
);

// Tool 4: extract_datatable
server.registerTool(
  'extract_datatable',
  {
    title: 'Extract DataTable',
    description: `Extract a UE5 DataTable asset to structured JSON. Includes the row struct schema and all row data.

USAGE GUIDELINES:
- Use search_assets first with class_filter "DataTable" to find the asset path.
- Returns the row struct type, property schema, row count, and all row data with names and values.
- Useful for understanding game data tables (items, abilities, stats, etc.).

RETURNS: JSON object with row struct info, schema, and all rows.`,
    inputSchema: {
      asset_path: z.string().describe(
        'UE content path to the DataTable (e.g. /Game/Data/DT_WeaponStats). Use search_assets to find paths.',
      ),
    },
    annotations: {
      title: 'Extract DataTable',
      readOnlyHint: true,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: false,
    },
  },
  async ({ asset_path }) => {
    try {
      const result = await client.callSubsystem('ExtractDataTable', { AssetPath: asset_path });
      const parsed = JSON.parse(result);
      if (parsed.error) {
        return { content: [{ type: 'text' as const, text: `Error: ${parsed.error}` }], isError: true };
      }
      const text = JSON.stringify(parsed, null, 2);
      if (text.length > 200_000) {
        return { content: [{ type: 'text' as const, text: `Warning: Response is ${(text.length / 1024).toFixed(0)}KB — large DataTable.\n\n${text.substring(0, 200_000)}...\n[TRUNCATED]` }] };
      }
      return { content: [{ type: 'text' as const, text }] };
    } catch (e) {
      return { content: [{ type: 'text' as const, text: `Error: ${e instanceof Error ? e.message : String(e)}` }], isError: true };
    }
  },
);

// Tool 5: extract_cascade
server.registerTool(
  'extract_cascade',
  {
    title: 'Extract Cascade',
    description: `Extract multiple assets (Blueprint, AnimBlueprint, StateTree, DataAsset, DataTable) with automatic reference following for Blueprints and StateTrees. Follows parent classes, interfaces, component classes, and other Blueprint references up to max_depth levels deep.

USAGE GUIDELINES:
- Use when you need to understand an asset AND its dependencies (parent Blueprints, referenced Blueprints, etc.).
- Results are written to files on disk (in the project's configured output directory), NOT returned inline — the response only contains a summary with file paths and count.
- For a single asset without dependencies, prefer extract_blueprint or extract_statetree instead.
- Cycle-safe: won't extract the same asset twice.

RETURNS: Summary with extracted_count and output_directory path. Read the output files to inspect the data.`,
    inputSchema: {
      asset_paths: z.array(z.string()).describe(
        'Array of UE content paths to extract (e.g. ["/Game/Blueprints/BP_Character", "/Game/Blueprints/BP_Weapon"])',
      ),
      scope: scopeEnum.default('Full').describe(
        'Extraction depth applied to all assets. Full is the default since cascade is typically used for deep analysis.',
      ),
      max_depth: z.number().int().min(0).max(10).default(3).describe(
        'How many levels deep to follow references (0 = only the listed assets, 3 = default)',
      ),
      graph_filter: z.array(z.string()).optional().describe(
        'Filter to specific graphs by name. Use FunctionsShallow scope first to discover graph names, then pass the names you want here. Empty/omitted = extract all graphs. Example: ["EventGraph", "CalculateDamage"]',
      ),
      compact: z.boolean().default(false).describe(
        'When true, strips low-value fields and minifies JSON to reduce size by ~50-70%. Removes: pinId, posX/posY, graphGuid, autogeneratedDefaultValue, nodeComment (when empty), empty connections, empty default_value, empty sub_category. Replaces full exec pin type objects with the string "exec".',
      ),
    },
    annotations: {
      title: 'Extract Cascade',
      readOnlyHint: false, // writes files to disk
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: false,
    },
  },
  async ({ asset_paths, scope, max_depth, graph_filter, compact }) => {
    try {
      const result = await client.callSubsystem('ExtractCascade', {
        AssetPathsJson: JSON.stringify(asset_paths),
        Scope: scope,
        MaxDepth: max_depth,
        GraphFilter: graph_filter ? graph_filter.join(',') : '',
      });
      const parsed = JSON.parse(result);
      if (parsed.error) {
        return { content: [{ type: 'text' as const, text: `Error: ${parsed.error}` }], isError: true };
      }
      return { content: [{ type: 'text' as const, text: `Extracted ${parsed.extracted_count} assets to ${parsed.output_directory}` }] };
    } catch (e) {
      return { content: [{ type: 'text' as const, text: `Error: ${e instanceof Error ? e.message : String(e)}` }], isError: true };
    }
  },
);

// Tool 6: search_assets
server.registerTool(
  'search_assets',
  {
    title: 'Search Assets',
    description: `Search for UE5 assets by name. This is a lightweight lookup — use it FIRST to find correct asset paths before calling extract_blueprint, extract_statetree, extract_dataasset, or extract_datatable.

USAGE GUIDELINES:
- Always call this before any extract_* tool if you don't already have the exact asset path.
- Searches asset names (not full paths) — partial matches work (e.g. "Character" finds "BP_Character").
- Filter by class to narrow results: "Blueprint" (default), "AnimBlueprint", "StateTree", "DataTable", "WidgetBlueprint", "DataAsset", or empty string for all.

RETURNS: JSON array of objects with path, name, and class for each matching asset.`,
    inputSchema: {
      query: z.string().describe(
        'Search term to match against asset names. Partial matches work (e.g. "Player" finds "BP_PlayerCharacter").',
      ),
      class_filter: z.string().default('Blueprint').describe(
        'Filter by asset class. Common values: "Blueprint", "AnimBlueprint", "WidgetBlueprint", "StateTree", "DataTable", "DataAsset", or "" for all asset types.',
      ),
    },
    annotations: {
      title: 'Search Assets',
      readOnlyHint: true,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: false,
    },
  },
  async ({ query, class_filter }) => {
    try {
      const result = await client.callSubsystem('SearchAssets', { Query: query, ClassFilter: class_filter });
      const parsed = JSON.parse(result);
      if (parsed.error) {
        return { content: [{ type: 'text' as const, text: `Error: ${parsed.error}` }], isError: true };
      }
      return { content: [{ type: 'text' as const, text: JSON.stringify(parsed, null, 2) }] };
    } catch (e) {
      return { content: [{ type: 'text' as const, text: `Error: ${e instanceof Error ? e.message : String(e)}` }], isError: true };
    }
  },
);

// Tool 7: list_assets
server.registerTool(
  'list_assets',
  {
    title: 'List Assets',
    description: `List UE5 assets under a package path. Use this to browse directory contents when you don't know asset names. If you know (part of) the asset name, prefer search_assets instead — it's faster and doesn't require knowing the directory.

RETURNS: JSON array of objects with path, name, and class for each asset in the directory.`,
    inputSchema: {
      package_path: z.string().describe(
        'UE package path to list (e.g. /Game/Blueprints, /Game/AI). Use /Game to list from the Content root.',
      ),
      recursive: z.boolean().default(true).describe(
        'Whether to include assets in subdirectories.',
      ),
      class_filter: z.string().default('').describe(
        'Filter by asset class (e.g. "Blueprint", "StateTree"). Empty string returns all asset types.',
      ),
    },
    annotations: {
      title: 'List Assets',
      readOnlyHint: true,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: false,
    },
  },
  async ({ package_path, recursive, class_filter }) => {
    try {
      const result = await client.callSubsystem('ListAssets', {
        PackagePath: package_path,
        bRecursive: recursive,
        ClassFilter: class_filter,
      });
      const parsed = JSON.parse(result);
      if (parsed.error) {
        return { content: [{ type: 'text' as const, text: `Error: ${parsed.error}` }], isError: true };
      }
      return { content: [{ type: 'text' as const, text: JSON.stringify(parsed, null, 2) }] };
    } catch (e) {
      return { content: [{ type: 'text' as const, text: `Error: ${e instanceof Error ? e.message : String(e)}` }], isError: true };
    }
  },
);

// Start server
async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
}

main().catch((e) => {
  console.error('Fatal:', e);
  process.exit(1);
});
